name: Build and Push to Harbor

on:
  pull_request:
    branches:
      - 'main'
      - 'sprint**'
      - 'hotfix**'
  push:
    branches:
      - 'main'
      - 'sprint**'
      - 'hotfix**'
env:
  ENV: ${{ github.ref == 'refs/heads/main' && 'PROD' || startsWith(github.ref, 'refs/heads/sprint') && 'TEST' || 'DEV' }} # 根据分支控制环境
jobs:
  has-credentials:
    name: Check for Harbor secrets
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check for Harbor secrets
        run: |
          if [ -z "${{ secrets.HARBOR_TOKEN }}" ]; then
            echo "Error: HARBOR_TOKEN is not set"
            exit 1
          fi
          if [ -z "${{ secrets.HARBOR_URL }}" ]; then
            echo "Error: HARBOR_URL is not set"
            exit 1
          fi
          if [ -z "${{ secrets.HARBOR_USER }}" ]; then
            echo "Error: HARBOR_USER is not set"
            exit 1
          fi
          if [ -z "${{ ENV }}" ]; then
            echo "Error: ENV is not set"
            exit 1
          fi
  build-and-push:
    runs-on: self-hosted
    environment: TEST
    needs: has-credentials
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Harbor
        run: |
          echo "ENV: $ENV"
          echo "${{ secrets.HARBOR_TOKEN }}" | docker login https://${{ secrets.HARBOR_URL }} \
            -u ${{ secrets.HARBOR_USER }} --password-stdin
            
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.HARBOR_URL }}/nanhuinsight/your-image-name:latest .

      - name: Push to Harbor
        run: |
          docker push ${{ secrets.HARBOR_URL }}/nanhuinsight/your-image-name:latest
